### ISSUE TITLE
Use CSS flexbox and grid for more things

### ISSUE THREAD

**Issue by tobyzerner** [flarum/issue-archive#355]
I think it's pretty safe to start using flexbox. http://caniuse.com/#feat=flexbox

This will result in cleaner markup, styling, and easier theming.

**Comment by SychO9** [comment]
The goal here is mainly to stop using floats, absolute positioning and negative margins where possible, it made sense back when the design was created, but CSS has evolved and features like flexbox and grid are a much better solution.

Places where I think we should start using grid/flexbox:

* [x] **App-header** (including the header controls).
* [x] **DiscussionPage**: this one is better left as part of flarum/framework#3866 since the idea is to use `sideNavContainer` on all pages, which would I believe also allow flarum/framework#3541.
* [x] **Post/EventPost**
* [x] **DiscussionListItem** (https://github.com/flarum/framework/pull/3868)
* [x] **TagsPage**
* [x] **Dropdown-menu items**
* [x] **NotificationDropdown**
* [x] **IndexPage-toolbar**
* [x] **UserCard**

There might be some places I missed, but these are the main ones at least, in each case we should make sure that responsiveness is not affected by the change and that things still look good on different screen sizes.
